//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        public int HouseId { get; set; }
        public Nullable<int> Acreage { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public Nullable<int> Price { get; set; }
        public string Owner { get; set; }
        public string PhoneNumber { get; set; }
        public string City { get; set; }
        public string Type { get; set; }
        public string Utilities { get; set; }
        public Nullable<int> ImageId { get; set; }
        public string LinnkMap { get; set; }
        public string Link360 { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual Image Image { get; set; }
    }
}
